services:
  - type: web
    name: stage8-paystack
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:create_app --factory --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
